[project]
name = "llmpj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.9",
    "dotenv>=0.9.9",
    "gradio>=5.30.0",
    "ipykernel>=6.29.5",
    "openai>=1.79.0",
]
